version: '3.8'
services:
    pgdb:
        image: postgres
        environment:
            POSTGRES_DB: revisionzen
            POSTGRES_USER: ivan
            POSTGRES_PASSWORD: 040998Ih@
        volumes:
            - pgdbdata:/var/lib/postgresql/data
    django:
        build:
            context: ./RevisionZenBackend
        container_name: backend
        command: uvicorn RevisionZenBackend.asgi:application --host 0.0.0.0 --port 8080
        volumes:
            - ./RevisionZenBackend:/app
        ports:
            - "8080:8080"
        depends_on:
            - pgdb
        environment:
            DATABASE_HOST: 194.163.142.148
            DATABASE_NAME: revisionzen
            DATABASE_USER: ivan
            DATABASE_PASSWORD: 040998Ih@
            DATABASE_PORT: 5432
volumes:
    pgdbdata:
