version: '3.8'
services:
    db:
        image: postgres:13
        volumes:
            - postgres_data:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: ${DATABASE_NAME}
            POSTGRES_USER: ${DATABASE_USER}
            POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    web:
        build: .
        volumes:
            - .:/code
        ports:
            - "8000:8000"
        environment:
            - DATABASE_HOST=db
            - DATABASE_PORT=${DATABASE_PORT}
        depends_on:
            - db
        command: ["./entrypoint.sh"]
