version: '3.8'
services:
    django:
        build:
            context: ./RevisionZenBackend
        container_name: backend
        command: uvicorn RevisionZenBackend.asgi:application --host 0.0.0.0 --port 8080
        volumes:
            - ./RevisionZenBackend:/app
        ports:
            - "8080:8080"
        depends_on:
            - pgdb
    pgdb:
        image: postgres
        restart: always
        environment:
            POSTGRES_DB: revisionzen
            POSTGRES_USER: ivan
            POSTGRES_PASSWORD: 040998Ih@
        container_name: pgdb
        volumes:
            - pgdbdata:/var/lib/postgrsql/data
        ports:
            - "5432:5432"
volumes:
    pgdbdata: null