# Generated by Django 4.2.7 on 2023-11-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='word',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
