# Generated by Django 4.2.7 on 2023-11-27 21:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Cards', '0004_cardlist_shared_with_cardcollection'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardcollection',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='collections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cardlist',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='lists', to=settings.AUTH_USER_MODEL),
        ),
    ]
