name: Django CI/CD Pipeline

on: push

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Set up QEMU
                uses: docker/setup-qemu-action@v3

            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v3

            -   name: Login to DockerHub
                uses: docker/login-action@v3
                with:
                    username: ${{ secrets.DOCKER_USERNAME }}
                    password: ${{ secrets.DOCKER_PASSWORD }}

            -   name: Build and push Docker image
                uses: docker/build-push-action@v5
                with:
                    context: .
                    push: true
                    tags: dufi1928/django-back

    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
            -   name: Deploy to server and run migrations
                uses: appleboy/ssh-action@master
                host: ${{ secrets.HOST }}
                username: ${{ secrets.USERNAME }}
                key: ${{ secrets.SSH_KEY }}
                script: |
                    docker service create --image dufi1928/django-back:latest django-service
                    sleep 10
                    TASK_ID=$(docker service ps --filter 'desired-state=running' django-service -q --no-trunc | head -n1)
                    CONTAINER_ID=$(docker inspect --format '{{.Status.ContainerStatus.ContainerID}}' $TASK_ID)
                    docker exec $CONTAINER_ID python manage.py migrate