name: Django CI/CD Pipeline

on: push

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Set up QEMU
                uses: docker/setup-qemu-action@v3

            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v3

            -   name: Login to DockerHub
                uses: docker/login-action@v3
                with:
                    username: ${{ secrets.DOCKER_USERNAME }}
                    password: ${{ secrets.DOCKER_PASSWORD }}

            -   name: Build and push Docker image
                uses: docker/build-push-action@v5
                with:
                    context: .
                    push: true
                    tags: dufi1928/django-back:latest

    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
            -   name: Deploy to server and run migrations
                uses: appleboy/ssh-action@master
                with:
                    host: ${{ secrets.HOST }}
                    username: ${{ secrets.USERNAME }}
                    key: ${{ secrets.SSH_KEY }}
                    script: |
                        docker service ls | grep django-service && docker service update --image dufi1928/django-back:latest django-service || docker service create --name django-service --replicas 1 --publish published=8000,target=8000 dufi1928/django-back:latest
                        sleep 10
                        CONTAINER_ID=$(docker ps --filter "name=django-service" --format "{{.ID}}" | head -n 1)
                        if [ ! -z "$CONTAINER_ID" ]; then
                            docker exec $CONTAINER_ID python manage.py migrate
                        else
                            echo "Failed to find a running container for django-service"
                        fi
