name: Django CI/CD Pipeline

on: push

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Set up QEMU
                uses: docker/setup-qemu-action@v3

            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v3

            -   name: Login to DockerHub
                uses: docker/login-action@v3
                with:
                    username: ${{ secrets.DOCKER_USERNAME }}
                    password: ${{ secrets.DOCKER_PASSWORD }}

            -   name: Build and push Docker image
                uses: docker/build-push-action@v5
                with:
                    context: .
                    push: true
                    tags: dufi1928/django-back

    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
            -   name: Deploy to server and run migrations
                uses: appleboy/ssh-action@master
                with:
                    host: ${{ secrets.HOST }}
                    username: ${{ secrets.USERNAME }}
                    key: ${{ secrets.SSH_KEY }}
                    script: |
                        docker pull dufi1928/django-back
                        docker stop django-container || true
                        docker rm django-container || true
                        docker run -d --name django-container -p 80:8000 dufi1928/django-back:latest
                        docker exec django-container python manage.py migrate
